# Travis-Ci
language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
      dist: xenial

    - os: osx
      osx_image: xcode10.2
      language: shell

install: pip3 install -r requirements.txt --upgrade pip --upgrade setuptools  # all three OSes agree about 'pip3'

script:
  - python3 --version || python --version;
  #- pytest -spPf test_cli.py
  - pyinstaller --onefile click_cli.py --hidden-import click --clean --name="mv-cli"
  - mkdir maticvigil-cli
  - mv dist/mv-cli maticvigil-cli/
  - chmod +x maticvigil-cli/mv-cli
  - cp README.md maticvigil-cli/
  - ./maticvigil-cli/mv-cli -h
  - zip -r mv-cli-${TRAVIS_OS_NAME}.zip maticvigil-cli
  - mv mv-cli-${TRAVIS_OS_NAME}.zip dist/
  - ls dist/

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

before_deploy:
  - export TRAVIS_TAG="preview-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: T3n9IDdF69oPr6Zoib/ZZZ1e1IIh9iPCPM2+ZGRYII4rM0t4FvRkZmw0XaphL4Y7lT17OeJaGCL7gcVHyjiNfVTM81JMbGcDAFyJ8CW0MEurNY6uhx9G4VZYWkHf1OdIZ7l4nDo3239EcUgrCVUPNMryvbxpmSQaDwBAAPt8c0Pjp9OfbtBsdyVpyb0E861YM39XrrTcN4ELmy5qFfsSCK7DzRjzqmlaONsQrf18KiciqP9T4ARvDUhlGhNRf/zmqcNmfDxrzAU8m5KNrqedQnNRCL5DVg9EK3kSoFuD2By4x/gfqrttWhzh1ecM0wpZfuvSK+F2RN5+KTTMSTmUR3Ngyy1vgxqLI0j5474n2GLbmZ5t0omtqJ+hUoPOzWvcN59p/QS8pdNtdNLjRfiz/T0EyW5PgG0RCoaDhHREA2Jp5XBt5dx25JbfXigcXGnBZqhp3qm2q3HBzTiRincKG1k0VNFSByolkgBR1mZo5cPuZx/+yq4Ihl3JcaWyMuI9xIN8cXJMQnvIBJyU1rOJPodFmTtwRYrizXWYnX6pOBQB8xmFroWtnYBEa/rIsYmKWK25Xykp+tkZzBGMweERT9iM/EQkcZ+WK9w6K7WYwaizp9EJXjh2fOP5i9TrJQz92IS7NA7Isdsc9pEkP0m3TBSLEPvXoWfkNgBga7Vycpw=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    repo: blockvigil/maticvigil-cli
    branch: master
notifications:
  slack:
    secure: PnqTCJMmjpH68DT4OwndIVU53O19kHwuBaRPMvXnKrbhd6eC0aF6fvw6KdSq04RxCqwWi9z1H7SErL6L9VfNdtEtWDrFSx6Zhj6XlaVxJWKLVcetdEqBbhVn3zTgK1P2Z0aDUaiblhXhAmkkza427KOFWrOqK4/G/K7Sl7ocm8kWtB0RXH/30DhnU6ASq8Q3zHuF9Lgp8gifmFLlfo2NhW4NtRMa5Yfwyo+uDfikXq7+85Id8D/aNy846+4kqj0ImEFvR1Gyi7cbuZsdvjufwjbuJmKTIELJ5LYe7/uDC8JCjGkMjHwQCtKIoJX6zf5iKZn+zRRNS+ubUCRkvW4TmBQl7PV1JaDvLTdZHrocxPK8zw6opFRDNyqZNqEWUwBzZlUou1ydmxDn/JarIUDcVC8M0hd4G0v3do+dPuFoBacrlfLSZVIvBp2UOaHYn1TmPjMLp+ex1hSXc+K9htK2aCDMxBLkQ2JeG54XvUVzaNCnJ/ZS5sMliihMO894gGLgk7W8kvLF0mel3eONjJvBmPVjR8+4bRTAXdjr3HcwzhuyUTHQk+hPoQ1s3A3kvkLuqYNLsJLPuzJFPIHy4e/KELGs8UnRQj8V/JD4q3DSwEH9Z84UiITidqxApXBHj2xqJ6dL3Rx0YF6+vQkIc75IzM2etQqVBI/fZ8HgzpdGMOo=
